name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5
      - name: Set up JDK 1.8
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 1.8
      - name: Checking your code format
        run: sbt scalafmtCheckAll
      - name: Run tests
        run: |
          npm install jsdom
          sbt +macroUtils/publishLocal +testSuiteJS/test +testSuiteJVM/test demo/run 
